### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by cevaris** [matt-major/do-wrapper#59]
Not sure what is going on here...

Getting the following error
```
GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (/Users/acardenas/git/status/backend/node_modules/do-wrapper/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/Users/acardenas/git/status/backend/node_modules/do-wrapper/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  name: 'RequestError',
  code: 'ECONNREFUSED'
}
```

With the following code
```
const digitalOcean = new DigitalOcean('my token');
const response = await digitalOcean.account.get();
console.log(response);
```

Looks like this is an issue related to 
- https://github.com/sindresorhus/got/issues/876
- https://github.com/sindresorhus/got/issues/951

It would be hard to find the offending dependency that is affecting GOT since I have so many installed. 

Feel free to close, just making you aware that I cannot use do-wrapper because of this issue.

**Comment by darnfish** [comment]
+1, `cloudflare` cannot be used with `do-wrapper`

**Comment by drooopie** [comment]
> +1, `cloudflare` cannot be used with `do-wrapper`

Anyone has a workaround for this?
