### ISSUE TITLE
"cloudflare" npm package does not work with this package - ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by drooopie** [matt-major/do-wrapper#66]
When using both `cloudflare` and `do-wrapper` npm packages, all requests sent from `do-wrapper` will fail.

This is the error seen:
```
(node:16361) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (.../node_modules/do-wrapper/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (.../node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

All I did was `npm init` and `npm i cloudflare do-wrapper`
and this is the code used to reproduce the error:
```
import DigitalOcean from 'do-wrapper';
import Cloudflare from 'cloudflare';

const DO_ACCESS_TOKEN = '...';

const DO = new DigitalOcean.default(DO_ACCESS_TOKEN);

DO.regions.getAll().then(regions => console.log(regions));
```

Are there any quick workarounds?

**Comment by drooopie** [comment]
This is my package.json
```
  "dependencies": {
    "cloudflare": "^2.7.0",
    "do-wrapper": "^4.4.1"
  },
  "type": "module"
```

**Comment by matt-major** [comment]
@drooopie I can only guess right now that this is due to the fact `cloudflare` also relies on the `got` dependency, albeit a much older version than the one in `do-wrapper`.

I'm not too familiar with the `cloudflare` dependency, does it add any kind of "interception" to the network calls being made?
