### ISSUE TITLE
Why do I need to include a tag_name property when using dropletsGetAll() ? 

### ISSUE THREAD

**Issue by AlexanderProd** [matt-major/do-wrapper#9]
I'm trying to retrieve data about all my droplets using the following code
```
api.dropletsGetAll().then((data) => {
        console.log(data.body);
      }).catch((error) => {
        console.log(error.body);
      });
```

but i get the following error 
```
(node:35611) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag_name' of undefined
    at a.value (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/do-wrapper/dist/do-wrapper.js:1:2436)
    at Object.execute (/Users/alexanderhoerl/Developer/discord-music-bot/commands/server.js:24:11)
    at Client.client.on (/Users/alexanderhoerl/Developer/discord-music-bot/index.js:37:32)
    at Client.emit (events.js:182:13)
    at MessageCreateAction.handle (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:24:14)

    at MessageCreateHandler.handle (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageC
reate.js:5:53)
    at WebSocketPacketManager.handle (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacket
Manager.js:103:65)
    at WebSocketConnection.onPacket (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:3
16:35)
    at WebSocketConnection.onMessage (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:
279:10)
    at WebSocket.onMessage (/Users/alexanderhoerl/Developer/discord-music-bot/node_modules/ws/lib/event-target.js:120:16)
(node:35611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a c
atch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminat
e the Node.js process with a non-zero exit code.
```

even though in the DigitalOcean api documentation you don't need to specify any parameters when retrieving data to all droplets.

**Comment by matt-major** [comment]
@AlexanderProd this has been corrected as part of https://github.com/matt-major/do-wrapper/pull/7

Please pull the latest version (3.14.3) to resolve this.
